-- Community Hub — initial schema (spec §5)
-- Target: Neon Postgres. Single global community (plan.md: multi-community deferred).
-- All timestamps are timestamptz (UTC). Ids are opaque text (uuid/slug) generated by the app.
--
-- Constitution ties:
--   Art. IV  — public read / authenticated write: this schema is read by public GETs;
--              writes (M2) require a provisioned member row.
--   Art. VII — moderation is first-class: `hidden` flags + `reports` ship in v1.
--   Art. VIII— data minimization: members store only handle, display name, oauth sub.

CREATE TABLE IF NOT EXISTS members (
  id           TEXT PRIMARY KEY,
  handle       TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  oauth_sub    TEXT UNIQUE,                       -- GitHub OAuth subject (set in M2)
  roles        TEXT[] NOT NULL DEFAULT '{}',      -- e.g. {organizer}, {moderator}
  joined_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS events (
  id          TEXT PRIMARY KEY,
  title       TEXT NOT NULL,
  description TEXT,
  starts_at   TIMESTAMPTZ NOT NULL,
  ends_at     TIMESTAMPTZ,
  location    TEXT,                               -- physical location (nullable)
  url         TEXT,                               -- online URL (nullable); at least one of location/url expected
  host_id     TEXT REFERENCES members(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  hidden      BOOLEAN NOT NULL DEFAULT false      -- moderator hide (Art. VII)
);
CREATE INDEX IF NOT EXISTS events_starts_at_idx ON events (starts_at);
CREATE INDEX IF NOT EXISTS events_hidden_idx    ON events (hidden);

CREATE TABLE IF NOT EXISTS rsvps (
  id         TEXT PRIMARY KEY,
  event_id   TEXT NOT NULL REFERENCES events(id)  ON DELETE CASCADE,
  member_id  TEXT NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  state      TEXT NOT NULL CHECK (state IN ('going', 'interested', 'no')),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (event_id, member_id)                    -- one standing RSVP per member/event
);
CREATE INDEX IF NOT EXISTS rsvps_event_idx ON rsvps (event_id);

-- Live attendance, distinct from RSVP (spec FR-E4).
CREATE TABLE IF NOT EXISTS check_ins (
  id        TEXT PRIMARY KEY,
  event_id  TEXT NOT NULL REFERENCES events(id)  ON DELETE CASCADE,
  member_id TEXT NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (event_id, member_id)                    -- attendance counted once per member
);
CREATE INDEX IF NOT EXISTS check_ins_event_idx ON check_ins (event_id);

CREATE TABLE IF NOT EXISTS tasks (
  id          TEXT PRIMARY KEY,
  title       TEXT NOT NULL,
  description TEXT,
  status      TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'claimed', 'done')),
  due_at      TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  hidden      BOOLEAN NOT NULL DEFAULT false      -- moderator hide (Art. VII)
);
CREATE INDEX IF NOT EXISTS tasks_status_idx ON tasks (status);
CREATE INDEX IF NOT EXISTS tasks_hidden_idx ON tasks (hidden);

-- Task.claimedBy[] (spec §5) normalized as a join table so multiple members can sign up.
CREATE TABLE IF NOT EXISTS task_claims (
  task_id    TEXT NOT NULL REFERENCES tasks(id)   ON DELETE CASCADE,
  member_id  TEXT NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  claimed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (task_id, member_id)
);
CREATE INDEX IF NOT EXISTS task_claims_task_idx ON task_claims (task_id);

-- Opt-in presence, one row per member (spec §5, FR-P1). Clearing presence deletes the row.
CREATE TABLE IF NOT EXISTS presence (
  member_id  TEXT PRIMARY KEY REFERENCES members(id) ON DELETE CASCADE,
  status     TEXT NOT NULL,
  note       TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS presence_updated_idx ON presence (updated_at);

CREATE TABLE IF NOT EXISTS reports (
  id          TEXT PRIMARY KEY,
  target_type TEXT NOT NULL CHECK (target_type IN ('event', 'task', 'presence')),
  target_id   TEXT NOT NULL,
  reporter_id TEXT REFERENCES members(id) ON DELETE SET NULL,
  reason      TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved    BOOLEAN NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS reports_target_idx ON reports (target_type, target_id);
